---
title: "Mackenzie Thomson | CV"
---

## Education

-   **The University of British Columbia Vancouver** - *Masters of Geomatics for Environmental Management (MGEM)*

    Current

    Concentration: ArcGIS Pro, QGIS, Remote Sensing, R, Python, PostgreSQL, Database Management

-   **The University of British Columbia Okanagan** - *B.A. Major in Geography*

    May 2023

    Concentration: Earth Sciences, ESRI ArcGIS Products

## Teaching Assistantships

-   **The University of British Columbia** - *Geomatics for Natural Resource Management Laboratory Teaching Assistant*

    *Current*

    Support undergraduate students in applied geomatics labs, including GIS, remote sensing, and spatial data analysis for natural resource management. Provide technical guidance on workflows and troubleshooting to reinforce geospatial concepts and analytic accuracy. Assist with grading, lab evaluation, and instructional support to ensure consistency with course learning objectives.

-   **The University of British Columbia** - *Earth Systems Laboratory Teaching Assistant*

    August 2020 – December 2020

    Co-created engaging lesson plans that integrated real-world environmental issues. Provided individualized guidance to students during labs to deepen their understanding of scientific concepts and procedures. Managed assignment and exam grading with accuracy and consistency.

## Relevant Work Experience

-   **Chartwell Resource Group Ltd.** - *Jr. Forestry Field Technician*

    August 2024 – August 2025

    Collected, analyzed, and mapped data on tree stands to manage forest vegetation health, growth, and natural resources. Designed and established GPS-marked harvest block boundaries and access roads. Utilized ArcGIS Field Maps, QGIS, and RoadEng for effective data visualizations that support informed decision making. Supported the execution of hydro-based capital projects.  

-   **The City of Vancouver** - *Assistant Wildlife Technician*

    April 2023 – December 2023

    Assisted in the development and implementation of the Park Board’s Canada Goose Management Plan. Conducted field surveys to monitor goose population, habitat use, and behavior. Leveraged data collected in ArcGIS FieldMaps to inform management strategies. Collaborated with local stakeholders to ensure effective wildlife management.

-   **Tap & Barrel Group** - *Lead Server, Event Server, Shift Manager*

    May 2022 – April 2023

    Supervised shifts and coordinated a large team to ensure efficient service during daily operations and high-volume events. Demonstrated strong leadership, communication, and problem-solving skills while delivering high-quality customer service and supporting staff training and team development.

## Awards & Honors

-   **Dean’s List** - *The University of British Columbia*

    Achieved September 2018 – May 2023

    A designation that recognizes exceptional academic achievements. Awarded to students that receive an average of 85% or higher on at least 27 credits per session.

-   **Deputy Vice-Chancellor Scholarship** - *The University of British Columbia*

    Achieved September 2018 – May 2023

    Awarded to the top 10% of returning domestic students based on academic achievement in the previous year.

## Institutional Service

-   **The Hive** - *Bouldering Instructor*

    August 2022 – December 2023

    Taught beginner through advanced bouldering techniques to diverse groups, fostering skill development, safety awareness, and a supportive environment. Designed tailored training programs, accommodating various skill levels and learning styles.

## Professional Certifications

-   OFA1 – First Aid & CPR/AED Level

-   AST1 – Avalanche Skills Training & Safety Theory

-   ENV-050 – Approved Work Practices for Managing Riparian Vegetation

-   BCH ENV-041 – Wildlife Awareness

-   BCH ENV-028 – Heritage and Archaeology Awareness

-   BCH ENV-148 – Invasive Species Awareness
